# Generated by Django 2.2.6 on 2020-06-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
