# Generated by Django 2.2.6 on 2020-06-12 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_profile_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='new',
        ),
    ]
