# Generated by Django 3.0.6 on 2020-06-13 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20200613_0601'),
        ('clients', '0006_auto_20200613_0542'),
    ]

    operations = [
    ]
