# Generated by Django 3.0.6 on 2020-06-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_merge_20200613_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fb_page_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='fb_page_token',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
